import { Product } from "./types";

export const products: Product[] = [
  {
    id: 1,
    name: "SIGNATURE CHOCOLATE BOX - LUXURY DARK CHOCO",
    price: 300.0,
    originalPrice: 395.0,
    discount: "24%",
    image: "/product-grid/1.png",
    isBestSeller: true,
    category: "SIGNATURE BOX",
  },
  {
    id: 2,
    name: "HOLOGRAPHIC CHOCOLATE",
    price: 300.0,
    originalPrice: 395.0,
    discount: "24%",
    image: "/product-grid/2.png",
    category: "CHOCOLATE BARS",
  },
  {
    id: 3,
    name: "HOLOGRAPHIC CHOCOLATE",
    price: 300.0,
    originalPrice: 395.0,
    discount: "24%",
    image: "/product-grid/3.png",
    category: "CHOCOLATE BARS",
  },
  {
    id: 4,
    name: "HOLOGRAPHIC CHOCOLATE",
    price: 300.0,
    originalPrice: 395.0,
    discount: "24%",
    image: "/product-grid/4.png",
    isSoldOut: true,
    category: "CHOCOLATE BARS",
  },
  {
    id: 5,
    name: "SIGNATURE CHOCOLATE BOX",
    price: 300.0,
    originalPrice: 395.0,
    discount: "24%",
    image: "/product-grid/5.png",
    isBestSeller: true,
    category: "SIGNATURE BOX",
  },
  {
    id: 6,
    name: "HOLOGRAPHIC CHOCOLATE",
    price: 300.0,
    originalPrice: 395.0,
    discount: "24%",
    image: "/product-grid/6.png",
    category: "CHOCOLATE BARS",
  },
  {
    id: 7,
    name: "HOLOGRAPHIC CHOCOLATE",
    price: 300.0,
    originalPrice: 395.0,
    discount: "24%",
    image: "/product-grid/7.png",
    isSoldOut: true,
    category: "CHOCOLATE BARS",
  },
  {
    id: 8,
    name: "HOLOGRAPHIC CHOCOLATE",
    price: 300.0,
    originalPrice: 395.0,
    discount: "24%",
    image: "/product-grid/1.png",
    category: "CHOCOLATE BARS",
  },
  {
    id: 9,
    name: "SIGNATURE CHOCOLATE BOX",
    price: 300.0,
    originalPrice: 395.0,
    discount: "24%",
    image: "/product-grid/2.png",
    isBestSeller: true,
    category: "SIGNATURE BOX",
  },
  {
    id: 10,
    name: "CHOCOLATE CLUSTERS",
    price: 300.0,
    originalPrice: 300.0, // No discount
    image: "/product-grid/3.png",
    category: "CLUSTERS",
  },
  {
    id: 11,
    name: "GANACHE SELECTION",
    price: 250.0,
    originalPrice: 250.0, // No discount
    image: "/product-grid/4.png",
    isSoldOut: true,
    category: "CUT GANACHE",
  },
  {
    id: 12,
    name: "LUXURY PRALINE BOX",
    price: 395.0,
    originalPrice: 395.0, // No discount
    image: "/product-grid/5.png",
    category: "GIFTING TRAYS",
  },
];

export const categories = [
  "SHOW ALL",
  "SIGNATURE BOX",
  "CLUSTERS",
  "GIFTING TRAYS",
  "CUSTOM & CORPORATE",
  "CUT GANACHE",
  "CHOCOLATE SLABS",
  "CHOCOLATE BARS",
  "COMING SOON",
];
